model: yolo26n.pt
data: /Users/cmelicio/PycharmProjects/show-ball/resources/dataset/data.yaml

train:
  imgsz: 640
  epochs: 100
  batch: 8
  workers: 0
  patience: 20
  fraction: 1
  freeze: 0
  name: ball_yolo26

  cos_lr: false

