model: yolo26n.pt
data: /Users/cmelicio/PycharmProjects/show-ball/resources/dataset/data.yaml

train:
  imgsz: 640
  epochs: 100
  batch: 8
  workers: 0
  patience: 20
  fraction: 1
  freeze: 0
  name: ball_yolo26_cos_lr

# Color
  hsv_h: 0.015
  hsv_s: 0.5
  hsv_v: 0.4

  # Geometry
  scale: 0.3

  # Mixing
  mosaic: 0.0
  close_mosaic: 0

  cos_lr: true
  lr0: 0.002
  lrf: 0.01
